name: gpsadmin
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  json_serializable: ^3.2.5
  google_maps_flutter: ^2.0.3
  http: ^0.12.0+4
  dio: ^3.0.8
  geolocator: ^6.2.0
  provider: ^4.0.4
  url_launcher: ^6.0.2
  after_layout: ^1.1.0
  shared_preferences: ^2.0.5
  very_good_analysis: ^2.0.0
  material_design_icons_flutter: ^4.0.5955
  firebase_messaging: ^8.0.0-dev.15
  firebase_core: ^0.7.0
  flutter_local_notifications: ^4.0.0
  carousel_slider: ^2.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/movie_icons.png"
  adaptive_icon_background: "assets/icon/movie_icons.png"


flutter:

  uses-material-design: true
  assets:
    - assets/images/