name: gpsadmin
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  json_serializable: ^3.2.5
  google_maps_flutter: ^0.5.24+1
  http: ^0.12.0+4
  dio: ^3.0.8
  provider: ^4.0.4
  url_launcher: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/